defaults:
  - paths: local
  - dataset: dogs
  - optimizer: adam
hydra:
  run:
    dir: '${paths.output_dir}/${experiment_name}'

project_name: "conv_auto_encoder"
experiment_name: '${now:%Y-%m-%d_%H-%M-%S}_${dataset.name}_${optimizer.name}'
loss_fn: 'perceptual'
epochs : 30
save_interval: 3
vis_batches: 2