defaults:
  - paths: local
  - dataset: dogs
  - optimizer: adam
hydra:
  run:
    dir: ${paths.output_dir}/${experiment_name}
  sweep:
    dir: ${paths.output_dir}/${experiment_name}
    subdir: ${experiment_name}
project_name: "conv_auto_encoder"
experiment_name: '${now:%Y-%m-%d_%H-%M-%S}_${dataset.name}_${optimizer.name}'
loss_fn: 'perceptual'
epochs : 10
save_interval: 5
vis_batches: 2
batch_size: 8
seed: 24
pretrained: "" #"./ckpt/best.pth"
debug: False
tags:
  - ${dataset.name}
  - ${optimizer.name}
  - ${loss_fn}